# Install python
FROM public.ecr.aws/lambda/python:3.9

RUN ls
# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt


#fix opencv error
#RUN pip install opencv-python-headless
RUN pip install opencv-contrib-python-headless
#RUN pip install opencv-contrib-python

RUN pip install boto3
RUN pip install 'pymongo[srv]'
RUN pip install certifi

# Copy required files
COPY aws_lambda/app .

RUN mkdir -p models
COPY models models
RUN mkdir -p utils
COPY utils utils

COPY detect.py .
COPY export.py .
COPY hubconf.py .
COPY weights/yolov5l_k32_best.pt model.pt

COPY aws_lambda/SECRET_VARS.py .
COPY aws_lambda/cloud_utils.py .


# Set entry point
CMD ["lambda_predict_on_new_sviews.lambda_handler"]

# build sam: sam build -t template_no_auth.yaml
# then sam deploy --guided
